export const industryProfiles = {
  pichelaria: {
    id: 'pichelaria',
    name: 'Pichelaria',
    tagline: 'Chaves, fechaduras e serralharia',
    icon: '🔑',
    prefix: 'S',
    labels: {
      service: 'Serviço',
      services: 'Serviços',
      newService: 'Novo Serviço',
      parts: 'Peças',
      part: 'Peça',
      labor: 'Mão de Obra',
      otherCosts: 'Outros Custos',
      serviceDescPlaceholder: 'Ex: Troca de fechadura, duplicação de chaves...',
      newServiceSubtitle: 'Registar um novo serviço de pichelaria',
      emptyServices: 'Nenhum serviço registado.',
    },
  },
  serralharia: {
    id: 'serralharia',
    name: 'Serralharia',
    tagline: 'Portões, grades e estruturas metálicas',
    icon: '🔩',
    prefix: 'S',
    labels: {
      service: 'Serviço',
      services: 'Serviços',
      newService: 'Novo Serviço',
      parts: 'Materiais',
      part: 'Material',
      labor: 'Mão de Obra',
      otherCosts: 'Outros Custos',
      serviceDescPlaceholder: 'Ex: Reparação de portão, instalação de grade...',
      newServiceSubtitle: 'Registar um novo serviço de serralharia',
      emptyServices: 'Nenhum serviço registado.',
    },
  },
  eletricista: {
    id: 'eletricista',
    name: 'Eletricista',
    tagline: 'Instalações e reparações elétricas',
    icon: '⚡',
    prefix: 'E',
    labels: {
      service: 'Intervenção',
      services: 'Intervenções',
      newService: 'Nova Intervenção',
      parts: 'Materiais',
      part: 'Material',
      labor: 'Mão de Obra',
      otherCosts: 'Despesas',
      serviceDescPlaceholder: 'Ex: Instalação de quadro, reparação de tomada...',
      newServiceSubtitle: 'Registar uma nova intervenção elétrica',
      emptyServices: 'Nenhuma intervenção registada.',
    },
  },
  canalizador: {
    id: 'canalizador',
    name: 'Canalizador',
    tagline: 'Canalização, fugas e instalações',
    icon: '🔧',
    prefix: 'C',
    labels: {
      service: 'Serviço',
      services: 'Serviços',
      newService: 'Novo Serviço',
      parts: 'Materiais',
      part: 'Material',
      labor: 'Mão de Obra',
      otherCosts: 'Despesas',
      serviceDescPlaceholder: 'Ex: Reparação de fuga, substituição de torneira...',
      newServiceSubtitle: 'Registar um novo serviço de canalização',
      emptyServices: 'Nenhum serviço registado.',
    },
  },
  mecanica: {
    id: 'mecanica',
    name: 'Mecânica Auto',
    tagline: 'Reparação e manutenção automóvel',
    icon: '🚗',
    prefix: 'M',
    labels: {
      service: 'Ordem de Serviço',
      services: 'Ordens de Serviço',
      newService: 'Nova Ordem',
      parts: 'Peças',
      part: 'Peça',
      labor: 'Mão de Obra',
      otherCosts: 'Despesas',
      serviceDescPlaceholder: 'Ex: Mudança de óleo, reparação de travões...',
      newServiceSubtitle: 'Registar uma nova ordem de serviço',
      emptyServices: 'Nenhuma ordem registada.',
    },
  },
  informatica: {
    id: 'informatica',
    name: 'Informática',
    tagline: 'Reparação e suporte técnico',
    icon: '💻',
    prefix: 'I',
    labels: {
      service: 'Atendimento',
      services: 'Atendimentos',
      newService: 'Novo Atendimento',
      parts: 'Componentes',
      part: 'Componente',
      labor: 'Mão de Obra',
      otherCosts: 'Despesas',
      serviceDescPlaceholder: 'Ex: Formatação, substituição de ecrã...',
      newServiceSubtitle: 'Registar um novo atendimento técnico',
      emptyServices: 'Nenhum atendimento registado.',
    },
  },
  geral: {
    id: 'geral',
    name: 'Serviços Gerais',
    tagline: 'Gestão de serviços e clientes',
    icon: '📋',
    prefix: 'S',
    labels: {
      service: 'Serviço',
      services: 'Serviços',
      newService: 'Novo Serviço',
      parts: 'Itens',
      part: 'Item',
      labor: 'Mão de Obra',
      otherCosts: 'Outros Custos',
      serviceDescPlaceholder: 'Descrição do serviço...',
      newServiceSubtitle: 'Registar um novo serviço',
      emptyServices: 'Nenhum serviço registado.',
    },
  },
}

export const industryList = Object.values(industryProfiles)

export function getIndustryProfile(id) {
  return industryProfiles[id] || industryProfiles.geral
}
